language: java
jdk:
  - openjdk8
  - oraclejdk8
env:
  global:
    - secure: "JzptRMU0Ul+AcvHKBQDj++HCnvYMLj5rxaW8VPM6VJG1MC8SOfEMHO1P9yRyPLP5jaw0WPI88BfPaI1LhSr3YPTiOgwCZWWbwtImJVvFdyVJm9ZCbsDExJcIVp5WDX0x0hI3m5QL+JVL4Yf9Bb6EkCD0EwA2XNDrO1hfHmWE5t8="
  matrix:
    - IDEA_VERSION=13.0.5
    - IDEA_VERSION=13.1.7
    - IDEA_VERSION=14.1.7
    - IDEA_VERSION=15.0.6
    - IDEA_VERSION=2016.3.8
    - IDEA_VERSION=2017.3.6
    - IDEA_VERSION=2018.1.7
    - IDEA_VERSION=2018.2.7
    - IDEA_VERSION=2018.3.4
install:
  - IDEA_TAR=ideaIC-${IDEA_VERSION}.tar.gz
  - |
    if [ -f ~/$IDEA_TAR ]; then
        echo "Copying existing IDEA archive."
        cp ~/$IDEA_TAR .
    else
        echo "Downloading IDEA archive."
        travis_retry wget https://download.jetbrains.com/idea/$IDEA_TAR -P ~
        echo "Copying IDEA archive."
        cp ~/$IDEA_TAR .
    fi
  - echo "Removing existing IDEA installation."
  - rm -rf idea-IC-*
  - echo "Installing IDEA to idea-IC/"
  - tar zxf $IDEA_TAR
  - rm -rf $IDEA_TAR
  - mv idea-IC-* idea-IC
  - echo "Creating build.properties file for ant."
  - echo "idea.home=$(pwd)/idea-IC" > build.properties
script: ant
